version: '3.7'

services:
    db:
        image: 'mysql:8.0.32'
        restart: always
        container_name: db
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: app
            MYSQL_PASSWORD: password
            MYSQL_USER: app
        ports:
            - 3306:3306
        volumes:
            - database_data:/var/lib/mysql
            - ./docker:/docker-entrypoint-initdb.d

    adminer:
        image: adminer
        container_name: adminer
        restart: always
        ports:
        - 8080:8080
    web:
        image: nginx:1.23.3
        container_name: web
        ports:
            - "8008:80" # access via 127.0.0.1:8008
        volumes:
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
    app:
        build:
            context: .
        container_name: app
        depends_on:
            - db

volumes:
    database_data:

networks:
    app_net:
        driver: bridge
