version: '3.7'

services:
    db:
        image: 'mysql:8.0.32'
        restart: always
        container_name: db
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: app
            MYSQL_PASSWORD: password
            MYSQL_USER: app
        ports:
            - 3306:3306
        volumes:
           - ./docker:/docker-entrypoint-initdb.d

    adminer:
        image: adminer
        container_name: adminer
        restart: always
        ports:
        - 8080:8080
    web:
        image: nginx:1.23.3
        container_name: web
        ports:
            - "8008:80" # access via 127.0.0.1:8000
        volumes:
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
    app:
        build:
            context: .
        container_name: app
        depends_on:
            - db
        environment:
            - APP_ENV=dev
            - APP_DEBUG=true
            - APP_SECRET=eccff223cfa8af3f50e16c96c432be61
        #     - APP_URL=http://localhost:8008/books
            # - DATABASE_URL="mysql://root:password@db:3306/app;serverVersion=8&charset=utf8mb4"

        # volumes:
            # - ./:/app
            # - ./.env:/.env

volumes:
    database_data:

networks:
    app_net:
        driver: bridge
